package ps;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Desc_vendas;
import model.bean.Vendas;
import model.dao.Desc_vendasDAO;
import model.dao.VendasDAO;

public class TelaFinanceiro extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaFinanceiro
     */
    public TelaFinanceiro() {
        initComponents();
        
        DefaultTableModel modelo1 = (DefaultTableModel) jTVendas.getModel();
        jTVendas.setRowSorter(new TableRowSorter(modelo1));
        
        DefaultTableModel modelo2 = (DefaultTableModel) jTDesc_venda.getModel();
        jTDesc_venda.setRowSorter(new TableRowSorter(modelo2));
        
        readJTable1();
        readJTable2();
    }
    
     public void readJTable1() {
        
        DefaultTableModel modelo1 = (DefaultTableModel) jTVendas.getModel();
        VendasDAO vdao = new VendasDAO();
        modelo1.setNumRows(0);

        for (Vendas v : vdao.read()) {
            modelo1.addRow(new Object[]{
                v.getId(),
                v.getData(),
                v.getValor()
            });

        }
    }
     
    public void readJTable2() {
        
        DefaultTableModel modelo2 = (DefaultTableModel) jTDesc_venda.getModel();
        Desc_vendasDAO dvdao = new Desc_vendasDAO();
        modelo2.setNumRows(0);

        for (Desc_vendas dv : dvdao.read()) {
            modelo2.addRow(new Object[]{
                dv.getId_venda(),
                dv.getNome(),
                dv.getQntd_vendida()
            });

        }
    }
    
      public void readJTableParaData(String DataPesquisa) {
                
        DefaultTableModel modelo = (DefaultTableModel) jTVendas.getModel();
        VendasDAO vdao = new VendasDAO();
        modelo.setNumRows(0);

        for (Vendas v : vdao.readParaData(DataPesquisa)) {
            modelo.addRow(new Object[]{
                v.getId(),
                v.getData(),
                v.getValor()
                
            });

        }

    }

       public void readJTableParaId_vendas(String DataPesquisa) {
                
        DefaultTableModel modelo = (DefaultTableModel) jTDesc_venda.getModel();
        Desc_vendasDAO dvdao = new Desc_vendasDAO();
        modelo.setNumRows(0);

        for (Desc_vendas v : dvdao.readParaId_venda(DataPesquisa)) {
            modelo.addRow(new Object[]{
                v.getId_venda(),
                v.getNome(),
                v.getQntd_vendida()
                
            });

        }

    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jDataVenda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTVendas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jProdutosPesquisa1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTDesc_venda = new javax.swing.JTable();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Data:");

        jDataVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDataVendaActionPerformed(evt);
            }
        });
        jDataVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDataVendaKeyReleased(evt);
            }
        });

        jTVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DATA", "VALOR"
            }
        ));
        jTVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTVendasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTVendas);
        if (jTVendas.getColumnModel().getColumnCount() > 0) {
            jTVendas.getColumnModel().getColumn(0).setMinWidth(80);
            jTVendas.getColumnModel().getColumn(0).setMaxWidth(80);
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Id_venda");

        jProdutosPesquisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProdutosPesquisa1ActionPerformed(evt);
            }
        });
        jProdutosPesquisa1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jProdutosPesquisa1KeyReleased(evt);
            }
        });

        jTDesc_venda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_VENDA", "PRODUTO", "QNTD VENDIDA"
            }
        ));
        jTDesc_venda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTDesc_vendaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTDesc_venda);
        if (jTDesc_venda.getColumnModel().getColumnCount() > 0) {
            jTDesc_venda.getColumnModel().getColumn(0).setMinWidth(80);
            jTDesc_venda.getColumnModel().getColumn(0).setMaxWidth(80);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jProdutosPesquisa1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jProdutosPesquisa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDataVendaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDataVendaKeyReleased
        readJTableParaData(jDataVenda.getText());
    }//GEN-LAST:event_jDataVendaKeyReleased

    private void jTVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTVendasMouseClicked

    }//GEN-LAST:event_jTVendasMouseClicked

    private void jDataVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDataVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDataVendaActionPerformed

    private void jProdutosPesquisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProdutosPesquisa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jProdutosPesquisa1ActionPerformed

    private void jProdutosPesquisa1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jProdutosPesquisa1KeyReleased
        readJTableParaId_vendas(jProdutosPesquisa1.getText());       
    }//GEN-LAST:event_jProdutosPesquisa1KeyReleased

    private void jTDesc_vendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTDesc_vendaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDesc_vendaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jDataVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jProdutosPesquisa1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTDesc_venda;
    private javax.swing.JTable jTVendas;
    // End of variables declaration//GEN-END:variables
}
